-- EcoGuard administrator roles and single-location isolation.
-- Run in the Supabase SQL Editor after backing up the affected tables.

alter table public.profiles add column if not exists location_id bigint;

do $$
declare constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%role%'
  loop
    execute format('alter table public.profiles drop constraint %I', constraint_name);
  end loop;
end $$;

update public.profiles set role = 'location_admin' where role = 'admin';

-- Assign each migrated location_admin a location_id, then synchronize trusted JWT claims.
-- Example (replace values):
-- update public.profiles set location_id = 1 where id = 'USER_UUID';
-- update auth.users u
-- set raw_app_meta_data = coalesce(u.raw_app_meta_data, '{}'::jsonb)
--   || jsonb_build_object('role', p.role, 'location_id', p.location_id)
-- from public.profiles p
-- where u.id = p.id and p.role in ('location_admin', 'super_admin');

alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
  check (role in ('tourist', 'pending_location_admin', 'location_admin', 'super_admin'));

alter table public.profiles
  drop constraint if exists profiles_location_id_fkey;

alter table public.profiles
  add constraint profiles_location_id_fkey
  foreign key (location_id) references public.ecological_locations(id) on delete restrict;

alter table public.profiles
  drop constraint if exists profiles_location_admin_assignment_check;

alter table public.profiles
  add constraint profiles_location_admin_assignment_check
  check (
    (role = 'location_admin' and location_id is not null)
    or (role <> 'location_admin' and location_id is null)
  ) not valid;

create index if not exists profiles_location_id_idx on public.profiles(location_id);
create index if not exists crowd_thresholds_location_id_idx on public.crowd_thresholds(location_id);
create index if not exists location_metrics_location_id_idx on public.location_metrics(location_id);

-- New and updated ecological destinations are limited to Peninsular Malaysia.
-- NOT VALID preserves any legacy East Malaysia rows while enforcing the rule
-- for every future INSERT or UPDATE.
alter table public.ecological_locations
  drop constraint if exists ecological_locations_west_malaysia_state_check;
alter table public.ecological_locations
  add constraint ecological_locations_west_malaysia_state_check
  check (state in (
    'Johor', 'Kedah', 'Kelantan', 'Melaka', 'Negeri Sembilan', 'Pahang',
    'Penang', 'Perak', 'Perlis', 'Selangor', 'Terengganu',
    'Kuala Lumpur', 'Putrajaya'
  )) not valid;

alter table public.ecological_locations
  drop constraint if exists ecological_locations_west_malaysia_coordinates_check;
alter table public.ecological_locations
  add constraint ecological_locations_west_malaysia_coordinates_check
  check (
    latitude between 1.0 and 6.85
    and longitude between 99.5 and 104.8
  ) not valid;

alter table public.ecological_locations
  drop constraint if exists ecological_locations_type_check;
alter table public.ecological_locations
  add constraint ecological_locations_type_check
  check (location_type in (
    'Cultural Site', 'World Heritage Site', 'National Park',
    'Tourist attractions', 'Geopark', 'Marine Park', 'Highland Reserve'
  )) not valid;

create table if not exists public.location_admin_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  requested_location_id bigint,
  requested_location_name text,
  requested_location_address text,
  requested_latitude double precision,
  requested_longitude double precision,
  requested_state text,
  location_method text not null default 'existing'
    check (location_method in ('existing', 'search', 'address')),
  company_document_path text not null,
  company_document_name text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint location_admin_applications_user_id_fkey
    foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint location_admin_applications_requested_location_id_fkey
    foreign key (requested_location_id) references public.ecological_locations(id) on delete restrict,
  constraint location_admin_applications_reviewed_by_fkey
    foreign key (reviewed_by) references public.profiles(id) on delete set null
);

alter table public.location_admin_applications
  alter column requested_location_id drop not null,
  add column if not exists requested_location_name text,
  add column if not exists requested_location_address text,
  add column if not exists requested_latitude double precision,
  add column if not exists requested_longitude double precision,
  add column if not exists requested_state text,
  add column if not exists location_method text not null default 'existing';

alter table public.location_admin_applications
  drop constraint if exists location_admin_applications_location_request_check;
alter table public.location_admin_applications
  drop constraint if exists location_admin_applications_location_method_check;
alter table public.location_admin_applications
  add constraint location_admin_applications_location_method_check
  check (location_method in ('existing', 'search', 'address')) not valid;
alter table public.location_admin_applications
  add constraint location_admin_applications_location_request_check check (
    (location_method = 'existing' and requested_location_id is not null)
    or
    (location_method in ('search', 'address') and requested_location_id is null
      and requested_location_name is not null
      and requested_latitude is not null
      and requested_longitude is not null)
  ) not valid;

create index if not exists location_admin_applications_status_idx
  on public.location_admin_applications(status, created_at desc);

-- Repair accounts rejected by the legacy flow, which incorrectly converted
-- applicants into tourists. Rejected applicants remain gated and may resubmit.
update public.profiles as profile
set role = 'pending_location_admin', location_id = null
from public.location_admin_applications as application
where application.user_id = profile.id
  and application.status = 'rejected'
  and profile.role = 'tourist';

update auth.users as auth_user
set raw_app_meta_data = (coalesce(auth_user.raw_app_meta_data, '{}'::jsonb) - 'location_id')
  || jsonb_build_object('role', 'pending_location_admin')
from public.location_admin_applications as application
where application.user_id = auth_user.id
  and application.status = 'rejected';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'company-documents',
  'company-documents',
  false,
  5242880,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Profile pictures are public display assets, but only their owner can write them.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-avatars',
  'profile-avatars',
  true,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists profile_avatars_owner_select on storage.objects;
drop policy if exists profile_avatars_owner_insert on storage.objects;
drop policy if exists profile_avatars_owner_update on storage.objects;
drop policy if exists profile_avatars_owner_delete on storage.objects;

create policy profile_avatars_owner_select on storage.objects
for select to authenticated
using (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy profile_avatars_owner_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy profile_avatars_owner_update on storage.objects
for update to authenticated
using (
  bucket_id = 'profile-avatars'
  and owner_id = (select auth.uid())::text
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'profile-avatars'
  and owner_id = (select auth.uid())::text
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy profile_avatars_owner_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'profile-avatars'
  and owner_id = (select auth.uid())::text
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create or replace function public.current_app_role()
returns text language sql stable
set search_path = ''
return coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), 'tourist');

create or replace function public.current_location_id()
returns bigint language sql stable
set search_path = ''
return nullif((select auth.jwt() -> 'app_metadata' ->> 'location_id'), '')::bigint;

revoke all on function public.current_app_role() from public;
revoke all on function public.current_location_id() from public;
grant execute on function public.current_app_role() to authenticated;
grant execute on function public.current_location_id() to authenticated;

grant select, insert, update, delete on table public.profiles to authenticated;
grant select, insert, update, delete on table public.ecological_locations to authenticated;
grant select, insert, update, delete on table public.crowd_thresholds to authenticated;
grant select, insert, update, delete on table public.location_metrics to authenticated;

alter table public.profiles enable row level security;
alter table public.ecological_locations enable row level security;
alter table public.crowd_thresholds enable row level security;
alter table public.location_metrics enable row level security;
alter table public.location_admin_applications enable row level security;

-- Replace existing policies so older broad "admin" policies cannot bypass this model.
do $$
declare item record;
begin
  for item in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('profiles', 'ecological_locations', 'crowd_thresholds', 'location_metrics')
  loop
    execute format('drop policy %I on %I.%I', item.policyname, item.schemaname, item.tablename);
  end loop;
end $$;

-- Applications and company documents are accessed only by the trusted backend.
-- The secret/service-role client bypasses RLS; browser roles receive no table policy.
revoke all on table public.location_admin_applications from anon, authenticated;

drop policy if exists company_documents_browser_select on storage.objects;
drop policy if exists company_documents_browser_insert on storage.objects;
drop policy if exists company_documents_browser_update on storage.objects;
drop policy if exists company_documents_browser_delete on storage.objects;

create policy profiles_read_own_or_super on public.profiles
for select to authenticated
using ((select auth.uid()) = id or (select public.current_app_role()) = 'super_admin');

create policy profiles_insert_own_tourist on public.profiles
for insert to authenticated
with check ((select auth.uid()) = id and role = 'tourist' and location_id is null);

create policy profiles_update_own_safe on public.profiles
for update to authenticated
using ((select auth.uid()) = id or (select public.current_app_role()) = 'super_admin')
with check (
  (
    (select auth.uid()) = id
    and role = (select public.current_app_role())
    and (
      (role = 'tourist' and location_id is null)
      or (
        role = 'location_admin'
        and location_id = (select public.current_location_id())
      )
    )
  )
  or (select public.current_app_role()) = 'super_admin'
);

create policy locations_read on public.ecological_locations
for select to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or (
    (select public.current_app_role()) = 'location_admin'
    and id = (select public.current_location_id())
  )
  or (
    (select public.current_app_role()) in ('tourist', 'pending_location_admin')
    and is_active
  )
);

create policy locations_insert_super on public.ecological_locations
for insert to authenticated
with check ((select public.current_app_role()) = 'super_admin');

create policy locations_update_admin on public.ecological_locations
for update to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or id = (select public.current_location_id())
)
with check (
  (select public.current_app_role()) = 'super_admin'
  or id = (select public.current_location_id())
);

create policy locations_delete_super on public.ecological_locations
for delete to authenticated
using ((select public.current_app_role()) = 'super_admin');

create policy thresholds_admin_scope on public.crowd_thresholds
for all to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or location_id = (select public.current_location_id())
)
with check (
  (select public.current_app_role()) = 'super_admin'
  or location_id = (select public.current_location_id())
);

create policy metrics_admin_scope on public.location_metrics
for all to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or location_id = (select public.current_location_id())
)
with check (
  (select public.current_app_role()) = 'super_admin'
  or location_id = (select public.current_location_id())
);

-- Public registration needs the active location list. Only SELECT is granted.
grant select on table public.ecological_locations to anon;
create policy locations_public_active_read on public.ecological_locations
for select to anon using (is_active);

-- Verification: no location admin should be missing an assignment before validating.
select id, full_name, role, location_id
from public.profiles
where role = 'location_admin' and location_id is null;

-- After fixing any returned rows, run:
-- alter table public.profiles validate constraint profiles_location_admin_assignment_check;
