-- Prevent multiple category webhooks from sending duplicate emails for the
-- same location sensor cycle. Apply once in the Supabase SQL Editor.

create table if not exists public.critical_alert_email_deliveries (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.ecological_locations(id) on delete cascade,
  sensor_recorded_at timestamptz not null,
  trigger_alert_id bigint references public.early_warning_alerts(id) on delete set null,
  gmail_message_id text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (location_id, sensor_recorded_at)
);

alter table public.critical_alert_email_deliveries enable row level security;
revoke all on public.critical_alert_email_deliveries from anon, authenticated;

