-- Persist early-warning alerts whenever a new environmental snapshot exceeds
-- a configured or safety threshold. Apply after admin_location_scope.sql and
-- waste_management.sql.

begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.early_warning_alerts (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.ecological_locations(id) on delete cascade,
  metric_id bigint not null references public.location_metrics(id) on delete cascade,
  category text not null check (category in ('crowd', 'waste', 'air_quality', 'water_quality', 'temperature')),
  severity text not null check (severity in ('caution', 'warning', 'critical')),
  title text not null,
  detail text not null,
  current_value numeric not null,
  threshold_value numeric not null,
  unit text not null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique (metric_id, category)
);

create index if not exists early_warning_alerts_location_created_idx
  on public.early_warning_alerts(location_id, created_at desc);
create unique index if not exists early_warning_alerts_one_active_category_idx
  on public.early_warning_alerts(location_id, category)
  where resolved_at is null;

create table if not exists public.early_warning_alert_reads (
  alert_id bigint not null references public.early_warning_alerts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (alert_id, user_id)
);

create index if not exists early_warning_alert_reads_user_idx
  on public.early_warning_alert_reads(user_id);

create or replace function private.record_early_warning(
  target_location_id bigint,
  target_metric_id bigint,
  target_category text,
  target_severity text,
  target_title text,
  target_detail text,
  target_value numeric,
  target_threshold numeric,
  target_unit text
)
returns void
language plpgsql
set search_path = ''
as $$
begin
  update public.early_warning_alerts
  set resolved_at = now()
  where location_id = target_location_id
    and category = target_category
    and resolved_at is null
    and severity is distinct from target_severity;

  if target_severity is null then
    update public.early_warning_alerts
    set resolved_at = now()
    where location_id = target_location_id
      and category = target_category
      and resolved_at is null;
    return;
  end if;

  if not exists (
    select 1 from public.early_warning_alerts
    where location_id = target_location_id
      and category = target_category
      and severity = target_severity
      and resolved_at is null
  ) then
    insert into public.early_warning_alerts (
      location_id, metric_id, category, severity, title, detail,
      current_value, threshold_value, unit
    ) values (
      target_location_id, target_metric_id, target_category, target_severity,
      target_title, target_detail, target_value, target_threshold, target_unit
    );
  end if;
end;
$$;

create or replace function private.evaluate_environmental_thresholds()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  location_name text;
  capacity numeric;
  crowd_alerts_enabled boolean;
  crowd_caution numeric;
  crowd_warning numeric;
  crowd_critical numeric;
  waste_moderate numeric;
  waste_high numeric;
  waste_critical numeric;
  alert_severity text;
  alert_threshold numeric;
  occupancy numeric;
begin
  select location.name, greatest(location.max_capacity, 1),
    coalesce(crowd.auto_alerts, true),
    coalesce(crowd.caution_percent, 60), coalesce(crowd.warning_percent, 80),
    coalesce(crowd.critical_percent, 90), waste.moderate_kg,
    waste.high_risk_kg, waste.critical_kg
  into location_name, capacity, crowd_alerts_enabled, crowd_caution,
    crowd_warning, crowd_critical, waste_moderate, waste_high, waste_critical
  from public.ecological_locations location
  left join public.crowd_thresholds crowd on crowd.location_id = location.id
  left join public.waste_thresholds waste on waste.location_id = location.id
  where location.id = new.location_id;

  occupancy := round((100 * new.crowd_count / capacity)::numeric, 1);
  alert_severity := null;
  alert_threshold := null;
  if crowd_alerts_enabled and occupancy >= crowd_critical then alert_severity := 'critical'; alert_threshold := crowd_critical;
  elsif crowd_alerts_enabled and occupancy >= crowd_warning then alert_severity := 'warning'; alert_threshold := crowd_warning;
  elsif crowd_alerts_enabled and occupancy >= crowd_caution then alert_severity := 'caution'; alert_threshold := crowd_caution;
  end if;
  perform private.record_early_warning(new.location_id, new.id, 'crowd', alert_severity,
    'Crowd threshold exceeded at ' || location_name,
    'Occupancy reached ' || occupancy || '% at ' || location_name || '.',
    occupancy, coalesce(alert_threshold, crowd_caution), '%');

  alert_severity := null;
  alert_threshold := null;
  if waste_critical is not null and new.waste_kg >= waste_critical then alert_severity := 'critical'; alert_threshold := waste_critical;
  elsif waste_high is not null and new.waste_kg >= waste_high then alert_severity := 'warning'; alert_threshold := waste_high;
  elsif waste_moderate is not null and new.waste_kg >= waste_moderate then alert_severity := 'caution'; alert_threshold := waste_moderate;
  end if;
  perform private.record_early_warning(new.location_id, new.id, 'waste', alert_severity,
    'Waste threshold exceeded at ' || location_name,
    'Stored waste reached ' || round(new.waste_kg, 1) || ' kg at ' || location_name || '.',
    new.waste_kg, coalesce(alert_threshold, waste_moderate, 0), 'kg');

  alert_severity := case when new.air_quality_index >= 200 then 'critical' when new.air_quality_index >= 150 then 'warning' when new.air_quality_index >= 100 then 'caution' end;
  alert_threshold := case alert_severity when 'critical' then 200 when 'warning' then 150 else 100 end;
  perform private.record_early_warning(new.location_id, new.id, 'air_quality', alert_severity,
    'Air-quality warning at ' || location_name,
    'Air Quality Index reached ' || new.air_quality_index || ' at ' || location_name || '.',
    new.air_quality_index, alert_threshold, 'AQI');

  alert_severity := case when new.water_quality_score <= 30 then 'critical' when new.water_quality_score <= 50 then 'warning' when new.water_quality_score <= 65 then 'caution' end;
  alert_threshold := case alert_severity when 'critical' then 30 when 'warning' then 50 else 65 end;
  perform private.record_early_warning(new.location_id, new.id, 'water_quality', alert_severity,
    'Water-quality warning at ' || location_name,
    'Water quality fell to ' || round(new.water_quality_score, 1) || '/100 at ' || location_name || '.',
    new.water_quality_score, alert_threshold, 'score');

  if new.temperature_c is not null then
    alert_severity := case when new.temperature_c >= 45 then 'critical' when new.temperature_c >= 40 then 'warning' when new.temperature_c >= 35 then 'caution' end;
    alert_threshold := case alert_severity when 'critical' then 45 when 'warning' then 40 else 35 end;
    perform private.record_early_warning(new.location_id, new.id, 'temperature', alert_severity,
      'High-temperature warning at ' || location_name,
      'Temperature reached ' || round(new.temperature_c, 1) || ' C at ' || location_name || '.',
      new.temperature_c, alert_threshold, 'C');
  end if;

  return new;
end;
$$;

revoke all on function private.record_early_warning(bigint, bigint, text, text, text, text, numeric, numeric, text) from public, anon, authenticated;
revoke all on function private.evaluate_environmental_thresholds() from public, anon, authenticated;

drop trigger if exists location_metrics_generate_early_warnings on public.location_metrics;
create trigger location_metrics_generate_early_warnings
after insert on public.location_metrics
for each row execute function private.evaluate_environmental_thresholds();

grant select on public.early_warning_alerts to authenticated;
grant select, insert on public.early_warning_alert_reads to authenticated;
grant usage, select on sequence public.early_warning_alerts_id_seq to authenticated;
revoke all on public.early_warning_alerts, public.early_warning_alert_reads from anon;

alter table public.early_warning_alerts enable row level security;
alter table public.early_warning_alert_reads enable row level security;

create policy early_warning_alerts_role_scope on public.early_warning_alerts
for select to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or location_id = (select public.current_location_id())
  or (
    (select public.current_app_role()) = 'tourist'
    and exists (
      select 1 from public.ecological_locations location
      where location.id = location_id and location.is_active
    )
  )
);

create policy early_warning_reads_own_select on public.early_warning_alert_reads
for select to authenticated using (user_id = (select auth.uid()));
create policy early_warning_reads_own_insert on public.early_warning_alert_reads
for insert to authenticated with check (
  user_id = (select auth.uid())
  and exists (select 1 from public.early_warning_alerts alert where alert.id = alert_id)
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'early_warning_alerts'
  ) then
    alter publication supabase_realtime add table public.early_warning_alerts;
  end if;
end $$;

commit;

-- Verification after applying:
-- Insert a location_metrics row above one configured threshold, then confirm:
-- select category, severity, title, resolved_at
-- from public.early_warning_alerts order by created_at desc;
