-- Optional EcoGuard Environmental Analytics history storage.
-- The analytics page works without this file by using current location_metrics rows.
-- Apply this after admin_location_scope.sql and sensor_current_metrics.sql when
-- day/week/month historical charts are required.

begin;

create table if not exists public.environmental_metric_history (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.ecological_locations(id) on delete cascade,
  metric_id bigint references public.location_metrics(id) on delete set null,
  crowd_count integer not null default 0 check (crowd_count >= 0),
  air_quality_index integer not null default 0 check (air_quality_index between 0 and 500),
  water_quality_score numeric(5,2) not null default 0 check (water_quality_score between 0 and 100),
  temperature_c numeric(5,2),
  source text not null default 'simulated',
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (metric_id, recorded_at)
);

create index if not exists environmental_metric_history_location_time_idx
  on public.environmental_metric_history(location_id, recorded_at desc);

create or replace function private.archive_environmental_metric()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.environmental_metric_history (
    location_id,
    metric_id,
    crowd_count,
    air_quality_index,
    water_quality_score,
    temperature_c,
    source,
    recorded_at
  ) values (
    new.location_id,
    new.id,
    new.crowd_count,
    new.air_quality_index,
    new.water_quality_score,
    new.temperature_c,
    coalesce(new.source, 'simulated'),
    new.recorded_at
  )
  on conflict (metric_id, recorded_at) do nothing;
  return new;
end;
$$;

revoke all on function private.archive_environmental_metric() from public, anon, authenticated;

drop trigger if exists location_metrics_archive_environmental_history
  on public.location_metrics;
create trigger location_metrics_archive_environmental_history
after insert or update on public.location_metrics
for each row execute function private.archive_environmental_metric();

insert into public.environmental_metric_history (
  location_id,
  metric_id,
  crowd_count,
  air_quality_index,
  water_quality_score,
  temperature_c,
  source,
  recorded_at
)
select
  location_id,
  id,
  crowd_count,
  air_quality_index,
  water_quality_score,
  temperature_c,
  coalesce(source, 'simulated'),
  recorded_at
from public.location_metrics
on conflict (metric_id, recorded_at) do nothing;

grant select on public.environmental_metric_history to authenticated;
revoke all on public.environmental_metric_history from anon;
alter table public.environmental_metric_history enable row level security;

drop policy if exists environmental_metric_history_admin_scope
  on public.environmental_metric_history;
create policy environmental_metric_history_admin_scope
on public.environmental_metric_history
for select to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or (
    (select public.current_app_role()) = 'location_admin'
    and location_id = (select public.current_location_id())
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'environmental_metric_history'
  ) then
    alter publication supabase_realtime add table public.environmental_metric_history;
  end if;
end $$;

commit;
