-- EcoGuard environmental analytics history and simulated-data backfill.
-- Apply after admin_location_scope.sql and sensor_current_metrics.sql.
-- Safe to run more than once: existing location/timestamp snapshots are skipped.

begin;

create table if not exists public.environmental_metric_history (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.ecological_locations(id) on delete cascade,
  metric_id bigint references public.location_metrics(id) on delete set null,
  crowd_count integer not null default 0 check (crowd_count >= 0),
  air_quality_index integer not null default 0 check (air_quality_index between 0 and 500),
  water_quality_score numeric(5,2) not null default 0 check (water_quality_score between 0 and 100),
  temperature_c numeric(5,2),
  source text not null default 'simulated',
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists environmental_metric_history_location_time_idx
  on public.environmental_metric_history(location_id, recorded_at desc);
create index if not exists environmental_metric_history_time_idx
  on public.environmental_metric_history(recorded_at desc);

-- Every future INSERT or UPDATE of the current sensor row is archived here.
create or replace function private.archive_environmental_metric()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.environmental_metric_history history
    where history.location_id = new.location_id
      and history.recorded_at = new.recorded_at
  ) then
    insert into public.environmental_metric_history (
      location_id, metric_id, crowd_count, air_quality_index,
      water_quality_score, temperature_c, source, recorded_at
    ) values (
      new.location_id, new.id, new.crowd_count, new.air_quality_index,
      new.water_quality_score, new.temperature_c,
      coalesce(new.source, 'simulated'), new.recorded_at
    );
  end if;
  return new;
end;
$$;

revoke all on function private.archive_environmental_metric()
  from public, anon, authenticated;

drop trigger if exists location_metrics_archive_environmental_history
  on public.location_metrics;
create trigger location_metrics_archive_environmental_history
after insert or update on public.location_metrics
for each row execute function private.archive_environmental_metric();

-- Generate one realistic simulated snapshot per location per hour, from
-- 1 Aug 2026 00:00 through 4 Sep 2026 12:00 (Malaysia time, inclusive).
with hourly_slots as (
  select generate_series(
    timestamptz '2026-08-01 00:00:00+08',
    timestamptz '2026-09-04 12:00:00+08',
    interval '1 hour'
  ) as recorded_at
), current_metrics as (
  select distinct on (metric.location_id)
    metric.location_id,
    metric.id as metric_id
  from public.location_metrics metric
  order by metric.location_id, metric.recorded_at desc, metric.id desc
), generated as (
  select
    location.id as location_id,
    current_metrics.metric_id,
    slot.recorded_at,
    greatest(0, least(location.max_capacity,
      round(location.max_capacity * (
        0.16
        + 0.42 * greatest(0, sin(pi() * (extract(hour from slot.recorded_at at time zone 'Asia/Kuala_Lumpur') - 6) / 14))
        + random() * 0.10
      ))
    ))::integer as crowd_count,
    greatest(20, least(180, round(42 + random() * 55
      + 12 * greatest(0, sin(pi() * extract(hour from slot.recorded_at at time zone 'Asia/Kuala_Lumpur') / 24))
    )))::integer as air_quality_index,
    round(greatest(55, least(99, 78 + random() * 16 - 4 * sin(extract(epoch from slot.recorded_at) / 86400)))::numeric, 1) as water_quality_score,
    round(greatest(23, least(36, 25 + random() * 3
      + 5 * greatest(0, sin(pi() * (extract(hour from slot.recorded_at at time zone 'Asia/Kuala_Lumpur') - 7) / 14))
    ))::numeric, 1) as temperature_c
  from public.ecological_locations location
  cross join hourly_slots slot
  left join current_metrics on current_metrics.location_id = location.id
)
insert into public.environmental_metric_history (
  location_id, metric_id, crowd_count, air_quality_index,
  water_quality_score, temperature_c, source, recorded_at
)
select
  generated.location_id, generated.metric_id, generated.crowd_count,
  generated.air_quality_index, generated.water_quality_score,
  generated.temperature_c, 'simulated_backfill', generated.recorded_at
from generated
where not exists (
  select 1
  from public.environmental_metric_history existing
  where existing.location_id = generated.location_id
    and existing.recorded_at = generated.recorded_at
);

grant select on public.environmental_metric_history to authenticated;
revoke all on public.environmental_metric_history from anon;
alter table public.environmental_metric_history enable row level security;

drop policy if exists environmental_metric_history_admin_scope
  on public.environmental_metric_history;
create policy environmental_metric_history_admin_scope
on public.environmental_metric_history
for select to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or (
    (select public.current_app_role()) = 'location_admin'
    and location_id = (select public.current_location_id())
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'environmental_metric_history'
  ) then
    alter publication supabase_realtime add table public.environmental_metric_history;
  end if;
end $$;

commit;

-- Verification:
-- select min(recorded_at), max(recorded_at), count(*)
-- from public.environmental_metric_history;
-- select source, count(*) from public.environmental_metric_history group by source;
