-- EcoGuard Waste Management Module
-- Phase 2 database schema, validation, indexes, audit data, and RLS.
--
-- Prerequisite:
--   Apply supabase/admin_location_scope.sql first. It creates the trusted
--   current_app_role() and current_location_id() authorization helpers.
--
-- Simulated current readings remain in public.location_metrics with
-- source = 'simulated'. They are deliberately separate from collection
-- schedules and collection-history records.

begin;

create schema if not exists extensions;
create extension if not exists btree_gist with schema extensions;
set local search_path = public, extensions;

do $$
begin
  if to_regclass('public.profiles') is null
    or to_regclass('public.ecological_locations') is null
    or to_regclass('public.location_metrics') is null then
    raise exception 'EcoGuard base tables are missing. Apply the base schema before waste_management.sql.';
  end if;

  if to_regprocedure('public.current_app_role()') is null
    or to_regprocedure('public.current_location_id()') is null then
    raise exception 'Apply supabase/admin_location_scope.sql before waste_management.sql.';
  end if;
end $$;

create table if not exists public.waste_collection_schedules (
  id bigint generated by default as identity primary key,
  location_id bigint not null,
  scheduled_for timestamptz not null,
  scheduled_until timestamptz not null,
  waste_type text not null,
  assigned_team text not null,
  status text not null default 'scheduled',
  notes text,
  created_by uuid not null default auth.uid(),
  updated_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint waste_collection_schedules_location_fkey
    foreign key (location_id)
    references public.ecological_locations(id)
    on delete restrict,
  constraint waste_collection_schedules_created_by_fkey
    foreign key (created_by)
    references public.profiles(id)
    on delete restrict,
  constraint waste_collection_schedules_updated_by_fkey
    foreign key (updated_by)
    references public.profiles(id)
    on delete restrict,
  constraint waste_collection_schedules_type_check
    check (waste_type in ('mixed', 'recyclable', 'organic', 'hazardous')),
  constraint waste_collection_schedules_status_check
    check (status in ('scheduled', 'completed', 'cancelled', 'missed')),
  constraint waste_collection_schedules_time_check
    check (scheduled_until > scheduled_for),
  constraint waste_collection_schedules_team_check
    check (length(btrim(assigned_team)) > 0),
  constraint waste_collection_schedules_id_location_unique
    unique (id, location_id),
  constraint waste_collection_schedules_no_overlap
    exclude using gist (
      location_id with =,
      tstzrange(scheduled_for, scheduled_until, '[)') with &&
    )
    where (status = 'scheduled')
);

comment on table public.waste_collection_schedules is
  'Planned waste-collection periods. Active schedules at one location cannot overlap.';
comment on column public.waste_collection_schedules.scheduled_for is
  'Inclusive collection-window start stored as timestamptz.';
comment on column public.waste_collection_schedules.scheduled_until is
  'Exclusive collection-window end stored as timestamptz.';

create table if not exists public.waste_collection_records (
  id bigint generated by default as identity primary key,
  schedule_id bigint,
  location_id bigint not null,
  collected_at timestamptz not null default now(),
  total_kg numeric(12, 2) not null default 0,
  recycled_kg numeric(12, 2) not null default 0,
  landfill_kg numeric(12, 2)
    generated always as (total_kg - recycled_kg) stored,
  waste_type text not null,
  status text not null,
  source text not null default 'manual',
  notes text,
  recorded_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),

  constraint waste_collection_records_schedule_unique
    unique (schedule_id),
  constraint waste_collection_records_schedule_location_fkey
    foreign key (schedule_id, location_id)
    references public.waste_collection_schedules(id, location_id)
    on delete restrict,
  constraint waste_collection_records_location_fkey
    foreign key (location_id)
    references public.ecological_locations(id)
    on delete restrict,
  constraint waste_collection_records_recorded_by_fkey
    foreign key (recorded_by)
    references public.profiles(id)
    on delete restrict,
  constraint waste_collection_records_type_check
    check (waste_type in ('mixed', 'recyclable', 'organic', 'hazardous')),
  constraint waste_collection_records_status_check
    check (status in ('completed', 'partial', 'missed')),
  constraint waste_collection_records_source_check
    check (source in ('manual', 'simulated_sensor')),
  constraint waste_collection_records_total_check
    check (total_kg >= 0),
  constraint waste_collection_records_recycled_check
    check (recycled_kg >= 0 and recycled_kg <= total_kg),
  constraint waste_collection_records_status_quantity_check
    check (
      (status = 'missed' and total_kg = 0 and recycled_kg = 0)
      or (status in ('completed', 'partial') and total_kg > 0)
    )
);

comment on table public.waste_collection_records is
  'Persisted results of scheduled or unscheduled waste-collection attempts.';
comment on column public.waste_collection_records.source is
  'manual or simulated_sensor; simulated records must be labelled in the UI and reports.';
comment on column public.waste_collection_records.landfill_kg is
  'Derived quantity equal to total_kg minus recycled_kg.';

create table if not exists public.waste_thresholds (
  location_id bigint primary key,
  moderate_kg numeric(12, 2) not null,
  high_risk_kg numeric(12, 2) not null,
  critical_kg numeric(12, 2) not null,
  updated_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint waste_thresholds_location_fkey
    foreign key (location_id)
    references public.ecological_locations(id)
    on delete cascade,
  constraint waste_thresholds_updated_by_fkey
    foreign key (updated_by)
    references public.profiles(id)
    on delete restrict,
  constraint waste_thresholds_order_check
    check (
      moderate_kg > 0
      and moderate_kg < high_risk_kg
      and high_risk_kg < critical_kg
    )
);

comment on table public.waste_thresholds is
  'Location-specific kilogram boundaries for Normal, Moderate, High Risk, and Critical waste levels.';

create table if not exists public.waste_report_exports (
  id bigint generated by default as identity primary key,
  location_id bigint,
  export_format text not null,
  period_start timestamptz,
  period_end timestamptz,
  record_count integer not null default 0,
  filters jsonb not null default '{}'::jsonb,
  generated_by uuid not null default auth.uid(),
  generated_at timestamptz not null default now(),

  constraint waste_report_exports_location_fkey
    foreign key (location_id)
    references public.ecological_locations(id)
    on delete restrict,
  constraint waste_report_exports_generated_by_fkey
    foreign key (generated_by)
    references public.profiles(id)
    on delete restrict,
  constraint waste_report_exports_format_check
    check (export_format in ('csv', 'pdf')),
  constraint waste_report_exports_record_count_check
    check (record_count >= 0),
  constraint waste_report_exports_period_check
    check (
      period_start is null
      or period_end is null
      or period_end >= period_start
    )
);

comment on table public.waste_report_exports is
  'Audit records for successful CSV and PDF waste-history exports.';
comment on column public.waste_report_exports.location_id is
  'Null only for a super-administrator report spanning multiple locations.';

create index if not exists waste_schedules_location_time_idx
  on public.waste_collection_schedules(location_id, scheduled_for desc);
create index if not exists waste_schedules_status_time_idx
  on public.waste_collection_schedules(status, scheduled_for);
create index if not exists waste_records_location_time_idx
  on public.waste_collection_records(location_id, collected_at desc);
create index if not exists waste_records_status_time_idx
  on public.waste_collection_records(status, collected_at desc);
create index if not exists waste_records_type_time_idx
  on public.waste_collection_records(waste_type, collected_at desc);
create index if not exists waste_exports_generated_by_time_idx
  on public.waste_report_exports(generated_by, generated_at desc);
create index if not exists waste_exports_location_time_idx
  on public.waste_report_exports(location_id, generated_at desc);

create or replace function public.can_manage_waste(target_location_id bigint)
returns boolean
language sql
stable
set search_path = ''
return (
  (select public.current_app_role()) = 'super_admin'
  or (
    (select public.current_app_role()) = 'location_admin'
    and target_location_id = (select public.current_location_id())
  )
);

revoke all on function public.can_manage_waste(bigint) from public;
grant execute on function public.can_manage_waste(bigint) to authenticated;

create or replace function public.complete_waste_collection(
  p_schedule_id bigint,
  p_collected_at timestamptz,
  p_total_kg numeric,
  p_recycled_kg numeric,
  p_status text,
  p_source text,
  p_notes text default null
)
returns public.waste_collection_records
language plpgsql
security invoker
set search_path = ''
as $$
declare
  schedule_row public.waste_collection_schedules%rowtype;
  collection_row public.waste_collection_records%rowtype;
  final_schedule_status text;
begin
  select *
  into schedule_row
  from public.waste_collection_schedules
  where id = p_schedule_id
  for update;

  if not found then
    raise exception using
      errcode = 'P0002',
      message = 'Waste collection schedule was not found.';
  end if;

  if not public.can_manage_waste(schedule_row.location_id) then
    raise exception using
      errcode = '42501',
      message = 'You are not authorized to complete this waste collection schedule.';
  end if;

  if schedule_row.status <> 'scheduled' then
    raise exception using
      errcode = '23514',
      message = 'Only an active scheduled collection can be completed or marked missed.';
  end if;

  final_schedule_status := case
    when p_status = 'missed' then 'missed'
    else 'completed'
  end;

  insert into public.waste_collection_records (
    schedule_id,
    location_id,
    collected_at,
    total_kg,
    recycled_kg,
    waste_type,
    status,
    source,
    notes,
    recorded_by
  ) values (
    schedule_row.id,
    schedule_row.location_id,
    p_collected_at,
    p_total_kg,
    p_recycled_kg,
    schedule_row.waste_type,
    p_status,
    p_source,
    nullif(btrim(p_notes), ''),
    auth.uid()
  )
  returning * into collection_row;

  update public.waste_collection_schedules
  set
    status = final_schedule_status,
    updated_by = auth.uid()
  where id = schedule_row.id;

  return collection_row;
end;
$$;

revoke all on function public.complete_waste_collection(
  bigint,
  timestamptz,
  numeric,
  numeric,
  text,
  text,
  text
) from public;
grant execute on function public.complete_waste_collection(
  bigint,
  timestamptz,
  numeric,
  numeric,
  text,
  text,
  text
) to authenticated;

create or replace function public.get_tourist_environmental_indicators()
returns table (
  location_id bigint,
  crowd_level text,
  warning_level text,
  environment_condition text,
  waste_level text,
  recycling_rate numeric,
  recorded_at timestamptz,
  data_source text
)
language sql
stable
security definer
set search_path = ''
as $$
  with latest_metric as (
    select distinct on (metric.location_id)
      metric.location_id,
      metric.crowd_count,
      metric.waste_kg,
      metric.recycled_kg,
      metric.air_quality_index,
      metric.water_quality_score,
      metric.recorded_at,
      metric.source
    from public.location_metrics metric
    order by metric.location_id, metric.recorded_at desc
  ), scored as (
    select
      location.id as location_id,
      metric.crowd_count,
      metric.waste_kg,
      metric.recycled_kg,
      metric.air_quality_index,
      metric.water_quality_score,
      metric.recorded_at,
      metric.source,
      100.0 * coalesce(metric.crowd_count, 0) / greatest(location.max_capacity, 1) as occupancy_percent,
      coalesce(crowd.caution_percent, 60) as caution_percent,
      coalesce(crowd.warning_percent, 80) as warning_percent,
      coalesce(crowd.critical_percent, 90) as critical_percent,
      waste.moderate_kg,
      waste.high_risk_kg,
      waste.critical_kg
    from public.ecological_locations location
    left join latest_metric metric on metric.location_id = location.id
    left join public.crowd_thresholds crowd on crowd.location_id = location.id
    left join public.waste_thresholds waste on waste.location_id = location.id
    where location.is_active
  )
  select
    scored.location_id,
    case
      when scored.recorded_at is null then 'Awaiting data'
      when scored.occupancy_percent >= scored.critical_percent then 'Critical'
      when scored.occupancy_percent >= scored.warning_percent then 'High'
      when scored.occupancy_percent >= scored.caution_percent then 'Moderate'
      else 'Low'
    end as crowd_level,
    case
      when scored.recorded_at is null then 'Awaiting data'
      when scored.occupancy_percent >= scored.critical_percent then 'Critical'
      when scored.occupancy_percent >= scored.warning_percent then 'High Risk'
      when scored.occupancy_percent >= scored.caution_percent then 'Caution'
      else 'Safe'
    end as warning_level,
    case
      when scored.recorded_at is null then 'Awaiting data'
      when scored.air_quality_index <= 50 and scored.water_quality_score >= 80 then 'Excellent'
      when scored.air_quality_index <= 100 and scored.water_quality_score >= 65 then 'Good'
      when scored.air_quality_index <= 150 and scored.water_quality_score >= 50 then 'Fair'
      else 'Poor'
    end as environment_condition,
    case
      when scored.recorded_at is null then 'Awaiting data'
      when scored.moderate_kg is null then 'Not configured'
      when scored.waste_kg >= scored.critical_kg then 'Critical'
      when scored.waste_kg >= scored.high_risk_kg then 'High Risk'
      when scored.waste_kg >= scored.moderate_kg then 'Moderate'
      else 'Normal'
    end as waste_level,
    case
      when scored.recorded_at is null or scored.waste_kg <= 0 then null
      else round((100.0 * scored.recycled_kg / scored.waste_kg)::numeric, 1)
    end as recycling_rate,
    scored.recorded_at,
    case
      when scored.recorded_at is null then 'unavailable'
      when scored.source = 'simulated' then 'simulated'
      else 'stored_estimate'
    end as data_source
  from scored
  order by scored.location_id;
$$;

comment on function public.get_tourist_environmental_indicators() is
  'Tourist-safe aggregate status bands. It never returns waste schedules, collection records, notes, or exact operational quantities.';

revoke all on function public.get_tourist_environmental_indicators() from public;
grant execute on function public.get_tourist_environmental_indicators() to authenticated;

create or replace function public.set_waste_row_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();

  if tg_table_name = 'waste_collection_schedules' then
    new.updated_by := coalesce(auth.uid(), new.updated_by, old.updated_by);
  elsif tg_table_name = 'waste_thresholds' then
    new.updated_by := coalesce(auth.uid(), new.updated_by, old.updated_by);
  end if;

  return new;
end;
$$;

create or replace function public.validate_future_waste_schedule()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'scheduled'
    and new.scheduled_for <= now()
    and (
      tg_op = 'INSERT'
      or new.scheduled_for is distinct from old.scheduled_for
      or new.status is distinct from old.status
    ) then
    raise exception using
      errcode = '22007',
      message = 'An active waste collection schedule must start in the future.';
  end if;

  return new;
end;
$$;

create or replace function public.validate_waste_collection_time()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.collected_at > now() then
    raise exception using
      errcode = '22007',
      message = 'Waste collection time cannot be in the future.';
  end if;

  return new;
end;
$$;

revoke all on function public.set_waste_row_updated_at() from public;
revoke all on function public.validate_future_waste_schedule() from public;
revoke all on function public.validate_waste_collection_time() from public;

drop trigger if exists waste_schedules_set_updated_at
  on public.waste_collection_schedules;
create trigger waste_schedules_set_updated_at
before update on public.waste_collection_schedules
for each row execute function public.set_waste_row_updated_at();

drop trigger if exists waste_thresholds_set_updated_at
  on public.waste_thresholds;
create trigger waste_thresholds_set_updated_at
before update on public.waste_thresholds
for each row execute function public.set_waste_row_updated_at();

drop trigger if exists waste_schedules_validate_future
  on public.waste_collection_schedules;
create trigger waste_schedules_validate_future
before insert or update on public.waste_collection_schedules
for each row execute function public.validate_future_waste_schedule();

drop trigger if exists waste_records_validate_collection_time
  on public.waste_collection_records;
create trigger waste_records_validate_collection_time
before insert on public.waste_collection_records
for each row execute function public.validate_waste_collection_time();

grant select, insert, update
  on table public.waste_collection_schedules to authenticated;
grant select, insert
  on table public.waste_collection_records to authenticated;
grant select, insert, update
  on table public.waste_thresholds to authenticated;
grant select, insert
  on table public.waste_report_exports to authenticated;

revoke all
  on table public.waste_collection_schedules,
           public.waste_collection_records,
           public.waste_thresholds,
           public.waste_report_exports
  from anon;

revoke delete
  on table public.waste_collection_schedules,
           public.waste_collection_records,
           public.waste_thresholds,
           public.waste_report_exports
  from authenticated;

grant usage, select on sequence public.waste_collection_schedules_id_seq
  to authenticated;
grant usage, select on sequence public.waste_collection_records_id_seq
  to authenticated;
grant usage, select on sequence public.waste_report_exports_id_seq
  to authenticated;

alter table public.waste_collection_schedules enable row level security;
alter table public.waste_collection_records enable row level security;
alter table public.waste_thresholds enable row level security;
alter table public.waste_report_exports enable row level security;

drop policy if exists waste_schedules_select_admin_scope
  on public.waste_collection_schedules;
create policy waste_schedules_select_admin_scope
on public.waste_collection_schedules
for select to authenticated
using ((select public.can_manage_waste(location_id)));

drop policy if exists waste_schedules_insert_admin_scope
  on public.waste_collection_schedules;
create policy waste_schedules_insert_admin_scope
on public.waste_collection_schedules
for insert to authenticated
with check (
  (select public.can_manage_waste(location_id))
  and created_by = (select auth.uid())
  and updated_by = (select auth.uid())
);

drop policy if exists waste_schedules_update_admin_scope
  on public.waste_collection_schedules;
create policy waste_schedules_update_admin_scope
on public.waste_collection_schedules
for update to authenticated
using ((select public.can_manage_waste(location_id)))
with check (
  (select public.can_manage_waste(location_id))
  and updated_by = (select auth.uid())
);

drop policy if exists waste_records_select_admin_scope
  on public.waste_collection_records;
create policy waste_records_select_admin_scope
on public.waste_collection_records
for select to authenticated
using ((select public.can_manage_waste(location_id)));

drop policy if exists waste_records_insert_admin_scope
  on public.waste_collection_records;
create policy waste_records_insert_admin_scope
on public.waste_collection_records
for insert to authenticated
with check (
  (select public.can_manage_waste(location_id))
  and recorded_by = (select auth.uid())
);

drop policy if exists waste_thresholds_select_admin_scope
  on public.waste_thresholds;
create policy waste_thresholds_select_admin_scope
on public.waste_thresholds
for select to authenticated
using ((select public.can_manage_waste(location_id)));

drop policy if exists waste_thresholds_insert_admin_scope
  on public.waste_thresholds;
create policy waste_thresholds_insert_admin_scope
on public.waste_thresholds
for insert to authenticated
with check (
  (select public.can_manage_waste(location_id))
  and updated_by = (select auth.uid())
);

drop policy if exists waste_thresholds_update_admin_scope
  on public.waste_thresholds;
create policy waste_thresholds_update_admin_scope
on public.waste_thresholds
for update to authenticated
using ((select public.can_manage_waste(location_id)))
with check (
  (select public.can_manage_waste(location_id))
  and updated_by = (select auth.uid())
);

drop policy if exists waste_exports_select_admin_scope
  on public.waste_report_exports;
create policy waste_exports_select_admin_scope
on public.waste_report_exports
for select to authenticated
using (
  (select public.current_app_role()) = 'super_admin'
  or (
    generated_by = (select auth.uid())
    and location_id is not null
    and (select public.can_manage_waste(location_id))
  )
);

drop policy if exists waste_exports_insert_admin_scope
  on public.waste_report_exports;
create policy waste_exports_insert_admin_scope
on public.waste_report_exports
for insert to authenticated
with check (
  generated_by = (select auth.uid())
  and (
    (
      location_id is not null
      and (select public.can_manage_waste(location_id))
    )
    or (
      location_id is null
      and (select public.current_app_role()) = 'super_admin'
    )
  )
);

commit;

-- Verification queries to run with separate accounts after applying:
--
-- select * from public.waste_collection_schedules order by scheduled_for;
-- select * from public.waste_collection_records order by collected_at desc;
-- select * from public.waste_thresholds order by location_id;
-- select * from public.waste_report_exports order by generated_at desc;
--
-- A location administrator must receive no rows for another location and must
-- receive an RLS error when trying to insert/update another location's data.
