import { encodePdf, fillRect, text } from './wasteReport.js'
import { numberValue, transportLabels } from './tripAnalytics.js'

export function buildAdminTripPdfBytes(trips = [], { generatedAt = new Date(), scope = 'Authorized administrator view' } = {}) {
  const totalDistance = trips.reduce((sum, trip) => sum + numberValue(trip.distance_km), 0)
  const totalEmission = trips.reduce((sum, trip) => sum + numberValue(trip.total_emission), 0)
  const pages = [summaryPage('EcoGuard Trip Report', scope, generatedAt, [
    ['Recorded trips', trips.length],
    ['Total distance', `${totalDistance.toFixed(2)} km`],
    ['Total emissions', `${totalEmission.toFixed(2)} kg CO2`],
  ])]
  for (let index = 0; index < trips.length; index += 21) pages.push(tripPage(trips.slice(index, index + 21), pages.length + 1))
  return encodePdf(pages)
}

export function buildEnvironmentalPdfBytes(metrics = [], locations = [], { generatedAt = new Date(), scope = 'Authorized administrator view' } = {}) {
  const names = Object.fromEntries(locations.map((location) => [String(location.id), location.name]))
  const averageAqi = metrics.length ? metrics.reduce((sum, row) => sum + numberValue(row.air_quality_index), 0) / metrics.length : 0
  const averageWater = metrics.length ? metrics.reduce((sum, row) => sum + numberValue(row.water_quality_score), 0) / metrics.length : 0
  const totalWaste = metrics.reduce((sum, row) => sum + numberValue(row.waste_kg), 0)
  const pages = [summaryPage('EcoGuard Environmental Report', scope, generatedAt, [
    ['Current readings', metrics.length],
    ['Total estimated waste', `${totalWaste.toFixed(2)} kg`],
    ['Average AQI', averageAqi.toFixed(1)],
    ['Average water quality', `${averageWater.toFixed(1)} / 100`],
  ])]
  for (let index = 0; index < metrics.length; index += 21) pages.push(environmentPage(metrics.slice(index, index + 21), names, pages.length + 1))
  return encodePdf(pages)
}

export function adminReportFilename(type, format, generatedAt = new Date()) {
  return `ecoguard-${type}-report-${generatedAt.toISOString().slice(0, 10)}.${format}`
}

function summaryPage(title, scope, generatedAt, cards) {
  const commands = []
  fillRect(commands, 0, 770, 595, 72, [0.05, 0.35, 0.28])
  text(commands, title, 42, 806, 20, 'F2', [1, 1, 1])
  text(commands, 'Filtered administrative report', 42, 787, 9, 'F1', [0.85, 1, 0.93])
  text(commands, `Generated: ${formatDate(generatedAt)}`, 42, 738, 10)
  text(commands, `Scope: ${truncate(scope, 82)}`, 42, 720, 9, 'F1', [0.35, 0.4, 0.48])
  cards.forEach(([label, value], index) => {
    const x = 42 + (index % 2) * 255
    const y = 660 - Math.floor(index / 2) * 75
    fillRect(commands, x, y - 38, 238, 54, [0.96, 0.98, 0.97])
    text(commands, label, x + 12, y - 3, 8, 'F1', [0.35, 0.4, 0.48])
    text(commands, String(value), x + 12, y - 24, 14, 'F2', [0.05, 0.35, 0.28])
  })
  text(commands, 'Detailed filtered records continue on the following pages.', 42, 430, 11, 'F2')
  text(commands, 'Generated by EcoGuard', 42, 48, 8, 'F1', [0.5, 0.55, 0.62])
  return commands.join('\n')
}

function tripPage(rows, pageNumber) {
  const commands = tableHeader('EcoGuard Trip Report', pageNumber, ['Date', 'Journey', 'Mode', 'Km', 'CO2', 'Points'], [36, 105, 332, 414, 466, 520])
  rows.forEach((trip, index) => {
    const y = 726 - index * 34
    if (index % 2 === 0) fillRect(commands, 34, y - 12, 527, 30, [0.97, 0.98, 0.98])
    text(commands, shortDate(trip.travelled_at), 36, y + 3, 7)
    text(commands, `${truncate(trip.starting_location, 21)} -> ${truncate(trip.destination, 23)}`, 105, y + 3, 7, 'F2')
    text(commands, trip.round_trip ? 'Round trip' : 'One way', 105, y - 8, 6, 'F1', [0.45, 0.5, 0.56])
    text(commands, truncate(transportLabels[trip.transport_mode] || trip.transport_mode || 'Unknown', 12), 332, y + 3, 7)
    text(commands, numberValue(trip.distance_km).toFixed(1), 414, y + 3, 7)
    text(commands, numberValue(trip.total_emission).toFixed(2), 466, y + 3, 7)
    text(commands, String(numberValue(trip.eco_points)), 520, y + 3, 7)
  })
  return commands.join('\n')
}

function environmentPage(rows, names, pageNumber) {
  const commands = tableHeader('EcoGuard Environmental Report', pageNumber, ['Date', 'Location', 'Visitors', 'Waste', 'AQI', 'Water'], [36, 105, 310, 375, 440, 500])
  rows.forEach((row, index) => {
    const y = 726 - index * 34
    if (index % 2 === 0) fillRect(commands, 34, y - 12, 527, 30, [0.97, 0.98, 0.98])
    text(commands, shortDate(row.recorded_at), 36, y + 3, 7)
    text(commands, truncate(names[String(row.location_id)] || `Location ${row.location_id}`, 30), 105, y + 3, 7, 'F2')
    text(commands, String(numberValue(row.crowd_count)), 310, y + 3, 7)
    text(commands, numberValue(row.waste_kg).toFixed(1), 375, y + 3, 7)
    text(commands, String(numberValue(row.air_quality_index)), 440, y + 3, 7)
    text(commands, numberValue(row.water_quality_score).toFixed(1), 500, y + 3, 7)
  })
  return commands.join('\n')
}

function tableHeader(title, pageNumber, headers, columns) {
  const commands = []
  text(commands, title, 36, 806, 15, 'F2')
  text(commands, `Detailed records - page ${pageNumber}`, 36, 789, 8, 'F1', [0.4, 0.45, 0.52])
  fillRect(commands, 34, 750, 527, 24, [0.05, 0.35, 0.28])
  headers.forEach((header, index) => text(commands, header, columns[index], 759, 7, 'F2', [1, 1, 1]))
  return commands
}

function shortDate(value) {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? 'Unknown' : new Intl.DateTimeFormat('en-MY', { day: '2-digit', month: 'short', year: '2-digit' }).format(date)
}

function formatDate(value) {
  return new Intl.DateTimeFormat('en-MY', { dateStyle: 'medium', timeStyle: 'short' }).format(value)
}

function truncate(value, length) {
  const clean = String(value || 'Not recorded')
  return clean.length > length ? `${clean.slice(0, length - 3)}...` : clean
}
