import { getTripTransportLabel, numberValue } from './tripAnalytics.js'
import { downloadWasteReport, encodePdf, fillRect, text } from './wasteReport.js'

const headers = [
  'Date',
  'Origin / Start Location',
  'Destination',
  'Ecological Location',
  'Transportation Mode',
  'Travel Distance (km)',
  'Carbon Emission per Traveller (kg CO2)',
  'Calculated Total Carbon Emission (kg CO2)',
  'Eco Points',
  'Passengers',
  'Trip Type',
]

export function buildTripHistoryCsv(trips = []) {
  const rows = trips.map((trip) => [
    formatExportDate(trip.travelled_at),
    trip.starting_location,
    trip.destination,
    trip.ecological_location_name || trip.ecological_location || '',
    getTripTransportLabel(trip),
    fixedNumber(trip.distance_km),
    fixedNumber(trip.carbon_emission),
    fixedNumber(trip.total_emission),
    numberValue(trip.eco_points),
    Math.max(1, numberValue(trip.passengers)),
    trip.round_trip ? 'Round trip' : 'One way',
  ])

  // A UTF-8 BOM keeps place names and other Unicode text readable in Excel.
  return `\uFEFF${[headers, ...rows].map((row) => row.map(csvCell).join(',')).join('\r\n')}`
}

export function tripHistoryFilename(generatedAt = new Date()) {
  return tripHistoryReportFilename('csv', generatedAt)
}

export function downloadTripHistoryCsv(trips, generatedAt = new Date()) {
  downloadWasteReport(buildTripHistoryCsv(trips), 'text/csv;charset=utf-8', tripHistoryReportFilename('csv', generatedAt))
}

export function buildTripHistoryPdfBytes(trips = [], { generatedAt = new Date() } = {}) {
  const createdAt = generatedAt instanceof Date ? generatedAt : new Date(generatedAt)
  const totalDistance = trips.reduce((sum, trip) => sum + numberValue(trip.distance_km), 0)
  const totalEmission = trips.reduce((sum, trip) => sum + numberValue(trip.total_emission), 0)
  const totalPoints = trips.reduce((sum, trip) => sum + numberValue(trip.eco_points), 0)
  const pages = [buildSummaryPage(trips, createdAt, { totalDistance, totalEmission, totalPoints })]

  for (let index = 0; index < trips.length; index += 20) {
    pages.push(buildTripTablePage(trips.slice(index, index + 20), pages.length + 1))
  }
  return encodePdf(pages)
}

export function tripHistoryReportFilename(format, generatedAt = new Date()) {
  return `ecoguard-my-trip-history-${generatedAt.toISOString().slice(0, 10)}.${format}`
}

export function downloadTripHistoryPdf(trips, generatedAt = new Date()) {
  const bytes = buildTripHistoryPdfBytes(trips, { generatedAt })
  downloadWasteReport(bytes, 'application/pdf', tripHistoryReportFilename('pdf', generatedAt))
}

function csvCell(value) {
  let text = String(value ?? '')
  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`
  return `"${text.replaceAll('"', '""')}"`
}

function fixedNumber(value) {
  return numberValue(value).toFixed(2)
}

function formatExportDate(value) {
  if (!value) return ''
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : date.toISOString()
}

function buildSummaryPage(trips, generatedAt, summary) {
  const commands = []
  fillRect(commands, 0, 770, 595, 72, [0.05, 0.35, 0.28])
  text(commands, 'EcoGuard Personal Trip History', 42, 806, 20, 'F2', [1, 1, 1])
  text(commands, 'Travel and sustainability report', 42, 787, 9, 'F1', [0.85, 1, 0.93])
  text(commands, `Generated: ${formatPdfDate(generatedAt)}`, 42, 738, 10)
  text(commands, 'Scope: Trips belonging to the signed-in tourist', 42, 720, 9, 'F1', [0.35, 0.4, 0.48])

  const cards = [
    ['Recorded trips', String(trips.length)],
    ['Total distance', `${summary.totalDistance.toFixed(2)} km`],
    ['Total carbon emission', `${summary.totalEmission.toFixed(2)} kg CO2`],
    ['Eco Points', String(summary.totalPoints)],
  ]
  cards.forEach(([label, value], index) => {
    const x = 42 + (index % 2) * 255
    const y = 665 - Math.floor(index / 2) * 74
    fillRect(commands, x, y - 38, 238, 54, [0.96, 0.98, 0.97])
    text(commands, label, x + 12, y - 3, 8, 'F1', [0.35, 0.4, 0.48])
    text(commands, value, x + 12, y - 24, 14, 'F2', [0.05, 0.35, 0.28])
  })

  text(commands, 'Report contents', 42, 480, 14, 'F2')
  text(commands, 'Date, route, ecological location when recorded, transportation mode,', 42, 454, 10)
  text(commands, 'distance, calculated carbon emissions, Eco Points, and trip details.', 42, 437, 10)
  if (trips.length) {
    fillRect(commands, 42, 350, 510, 54, [0.93, 0.98, 0.95])
    text(commands, 'Detailed trip rows continue on the following page(s).', 58, 380, 11, 'F2', [0.05, 0.35, 0.28])
  } else {
    fillRect(commands, 42, 350, 510, 54, [0.97, 0.98, 0.98])
    text(commands, 'No saved trips were available when this report was generated.', 58, 380, 11, 'F2', [0.35, 0.4, 0.48])
  }
  text(commands, 'Generated by EcoGuard', 42, 48, 8, 'F1', [0.5, 0.55, 0.62])
  return commands.join('\n')
}

function buildTripTablePage(trips, pageNumber) {
  const commands = []
  text(commands, 'EcoGuard Personal Trip History', 36, 806, 15, 'F2')
  text(commands, `Detailed journeys - page ${pageNumber}`, 36, 789, 8, 'F1', [0.4, 0.45, 0.52])
  fillRect(commands, 34, 750, 527, 24, [0.05, 0.35, 0.28])
  const columns = [36, 102, 330, 410, 462, 520]
  ;['Date', 'Journey', 'Mode', 'Km', 'CO2 kg', 'Points'].forEach((header, index) => {
    text(commands, header, columns[index], 759, 7, 'F2', [1, 1, 1])
  })

  trips.forEach((trip, index) => {
    const y = 726 - index * 34
    if (index % 2 === 0) fillRect(commands, 34, y - 12, 527, 30, [0.97, 0.98, 0.98])
    const mode = getTripTransportLabel(trip)
    text(commands, shortPdfDate(trip.travelled_at), columns[0], y + 3, 7)
    text(commands, `${truncate(trip.starting_location, 22)} -> ${truncate(trip.destination, 25)}`, columns[1], y + 3, 7, 'F2')
    const ecologicalLocation = trip.ecological_location_name || trip.ecological_location
    text(commands, ecologicalLocation ? `Ecological: ${truncate(ecologicalLocation, 44)}` : (trip.round_trip ? 'Round trip' : 'One way'), columns[1], y - 8, 6, 'F1', [0.45, 0.5, 0.56])
    text(commands, truncate(mode, 12), columns[2], y + 3, 7)
    text(commands, numberValue(trip.distance_km).toFixed(1), columns[3], y + 3, 7)
    text(commands, numberValue(trip.total_emission).toFixed(2), columns[4], y + 3, 7)
    text(commands, String(numberValue(trip.eco_points)), columns[5], y + 3, 7, 'F2', [0.05, 0.45, 0.3])
  })
  text(commands, 'CO2 values show the calculated total emission for each saved trip.', 36, 42, 7, 'F1', [0.45, 0.5, 0.56])
  return commands.join('\n')
}

function formatPdfDate(value) {
  return new Intl.DateTimeFormat('en-MY', { dateStyle: 'medium', timeStyle: 'short' }).format(value)
}

function shortPdfDate(value) {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return 'Unknown'
  return new Intl.DateTimeFormat('en-MY', { day: '2-digit', month: 'short', year: '2-digit' }).format(date)
}

function truncate(value, length) {
  const textValue = String(value || 'Not recorded')
  return textValue.length > length ? `${textValue.slice(0, length - 3)}...` : textValue
}
